-EUFI_english_part1(https://www.youtube.com/watch?v=t3iwBQg_Gik&list=PLDcIWJGH-eMjhHtcH0CfB0P-8k0SuJDNd&index=4)
    -necessary document (3:05)
    -install mingw (https://www.youtube.com/watch?v=MemMGcakCjk)
        ->sudo apt install mingw-w64
    -install qemu ubuntu (https://itsfoss.com/qemu-ubuntu/)
       ->LC_ALL=C lscpu | grep Virtualization
    -qemu-system-x86_64 (15:14)
-
    -
    -
    -
    -
